Added devShell in module-options build
numtide/treefmt-nix pull request #84
Opened 2023-06-13 08:17 UTC by eswar2001

Resolves #65 .

2023-06-13 14:51 UTC, srid requested changes

2023-06-13 14:51 UTC, srid commented on module-options.nix
> +        default = pkgs.mkShell { buildInputs = [ config.build.wrapper ] ++ (lib.attrValues config.build.programs); };
```suggestion
        default = pkgs.mkShell { nativeBuildInputs = [ config.build.wrapper ] ++ (lib.attrValues config.build.programs); };
```

(So you get shell completion, as @roberth says)

You probably also want to set `readonly = true;` in this option.

2023-06-14 16:49 UTC, srid approved these changes
LGTM

2023-06-22 17:02 UTC, zimbatm commented
It's fine, I'll squash the commits. Thanks for the contrib!

2023-06-22 17:02 UTC, merged